In [1]:
import numpy as np

In [27]:
np.arange(0,12) #ardışıık dizi

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
np.arange(15,5,-3) #15'ten başla 5'e kadar 3er geri yazdır.

array([15, 12,  9,  6])

In [31]:
np.linspace(1,2) #50 noktaya bölüyor

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

In [34]:
np.random.randint(1,10, (3,4,4)) #random dizi

array([[[3, 9, 6, 6],
        [2, 7, 9, 6],
        [9, 1, 2, 2],
        [4, 9, 1, 9]],

       [[5, 6, 8, 2],
        [7, 7, 4, 7],
        [9, 6, 3, 3],
        [1, 9, 8, 4]],

       [[9, 6, 3, 9],
        [6, 3, 8, 4],
        [2, 2, 7, 3],
        [3, 5, 3, 7]]], dtype=int32)

In [35]:
d = {}
for _ in range(20000):
    val = np.random.randint(1,11)

    if val not in d:
        d[val] = 1
    else:
        d[val] += 1

In [36]:
d # döngü 20000 kez dönüyor oluşturulan d dictionary içerisine 1'den 10'a kadar olan sayıların kaç kez geldiği kaydediliyor.

{8: 2030,
 7: 1964,
 1: 1993,
 10: 1980,
 4: 1992,
 5: 2001,
 9: 2058,
 6: 2033,
 3: 1967,
 2: 1982}

In [38]:
np.eye(3,3) #identity(birim) matris

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [5]:
x1 = np.array([1, 2, 3])
x2 = np.array([4, 5, 6])
#array çarpım
x1 * x2

array([ 4, 10, 18])

In [41]:
a = [4, 6, 7]
b = [213, 45, 564654]
#concat işlemi yapar
a + b

[4, 6, 7, 213, 45, 564654]

In [44]:
x = np.zeros((2,3,4))
print(x)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [45]:
x.ndim

3

In [4]:
a = np.arange(1, 11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
a.reshape(2, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [7]:
a = [1, 2, 3]
b = [4, 5, 6]
c = [7, 8, 9]
#concat birleştirme işlemi
np.concatenate([a, b, c])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
s = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#2. ve 6. indexlerden diziyi parçala
np.split(s, [2,6])

[array([0, 1]), array([2, 3, 4, 5]), array([6, 7, 8, 9])]